# Generated by Django 4.2.8 on 2023-12-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_alter_campus_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='arquivo',
            field=models.FileField(null=True, upload_to='img_campus/'),
        ),
    ]
