# Generated by Django 4.2.8 on 2023-12-29 18:00

import campus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_campus_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='arquivo',
            field=models.FileField(null=True, upload_to=campus.models.get_file_path),
        ),
    ]
