# Generated by Django 5.0 on 2023-12-18 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('Ensino Integrado', 'INTEGRADO'), ('Ensino Superior', 'SUPERIOR')], max_length=30, verbose_name='Tipo')),
                ('periodo', models.CharField(choices=[('Matutino', 'MATUTINO'), ('Vespertino', 'VESPERTINO'), ('Noturno', 'NOTURNO'), ('Integral', 'INTEGRAL')], max_length=45, verbose_name='Período')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus', verbose_name='Campus')),
            ],
        ),
    ]
